### ISSUE TITLE
Travis test failing

### ISSUE THREAD

**Issue by dahfool** [pmros/webdriverio-starter#3]
Hi @pmros, seems like the test is failing on Travis

[phantomjs #0-0] 1 failing (2s)

Any idea how to fix this ?

**Comment by pmros** [comment]
Hi @dahfool,
Last Travis build ([#10](https://travis-ci.org/pmros/webdriverio-starter/builds/223285181)) failed but it was willfully done. 
```
[phantomjs #0-0] 1) fixture has the expected page title:
[phantomjs #0-0] 'A very cool title' == 'End-to-End Testing'
```
I was simulating a wrong pull request, so tests failed.

If you are talking about another test, please give me more information.

**Comment by dahfool** [comment]
@pmros 👍 

I will close the issue
